def Print_Team_ID_and_Name():
    print("American League               National League")
    print("===============               ===============")
    print("-------                       -------")
    print("AL East                       NL East")
    print("-------                       -------")
    print("Baltimore Orioles-110" "         " "Atlanta Braves-144")
    print("Boston Red Sox-111" "            " "Miami Marlins-146")
    print("New York Yankees-147" "          " "New York Mets-121")
    print("Tampa Bay Rays-139" "            " "Philadelphia Phillies-143")
    print("Toronto Blue Jays-141"  "         " "Washington Nationals-120")
    print("----------                    ----------")
    print("AL Central                    NL Central")
    print("----------                    ----------")
    print("Chicago White Sox-145" "         " "Chicago Cubs-112")
    print("Cleveland Guardians-114" "       " "Cincinatti Reds-113")
    print("Detroit Tigers-116" "            " "Milwalkee Brewers-158")
    print("Kansas City Royals-118" "        " "Pittsburg Pirates-134")
    print("Minnesota Twins-142" "           " "St.Louis Cardinals-138")
    print("-------                       -------")
    print("AL West                       NL West")
    print("-------                       -------")
    print("Houston Astros-117" "            " "Arizona Diamondbacks-109")
    print("Los Angeles Angels-108" "        " "Colorado Rockies-115")
    print("Oakland Athletics-133" "         " "Los Angeles Dodgers-119")
    print("Seattle Mariners-136" "          " "San Diego Pagres-135")
    print("Texas Rangers-140" "             " "San Francisco Giants-137")

def Print_Menu_Options():
    print("========================================================================================================================")
    print("Play Ball:(1)")
    print("Team Record:(2)")
    print("Roster Managment:(3)")
    print("Trade Managment:(4)")
    print("Super Sim:(5)")
    print("End Program:(6)")
    print("========================================================================================================================")

    